[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated.
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below:
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[32mINFO[0m:     127.0.0.1:35868 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[2025-09-30 10:51:24,081][flwr][WARNING] - DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated.
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below:
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[2025-09-30 10:51:24,084][flwr][WARNING] - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[2025-09-30 10:51:24,114][flwr][DEBUG] - Opened insecure gRPC connection (no certificates were passed)
[2025-09-30 10:51:24,115][flwr][DEBUG] - ChannelConnectivity.IDLE
[2025-09-30 10:51:24,116][flwr][DEBUG] - ChannelConnectivity.CONNECTING
[2025-09-30 10:51:24,262][flwr][DEBUG] - ChannelConnectivity.TRANSIENT_FAILURE
[2025-09-30 10:51:24,464][flwr][DEBUG] - gRPC channel closed
--- Logging error ---
Traceback (most recent call last):
  File "/home/ccl/Desktop/RR/FedOps2/fedopstest/app.py", line 148, in fl_client_start
    await loop.run_in_executor(None, client_start)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 627, in start_numpy_client
    start_client(
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 184, in start_client
    start_client_internal(
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 395, in start_client_internal
    message = receive()
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/grpc_client/connection.py", line 142, in receive
    proto = next(server_message_iterator)
  File "/home/ccl/.local/lib/python3.9/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
  File "/home/ccl/.local/lib/python3.9/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.9.201.228:40002: Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.9.201.228:40002: Socket closed", grpc_status:14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/ccl/Desktop/RR/FedOps2/fedopstest/app.py", line 205, in fl_client_start
    logging.info('[E][PC0002] learning', e)
Message: '[E][PC0002] learning'
Arguments: (<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.9.201.228:40002: Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.9.201.228:40002: Socket closed", grpc_status:14}"
>,)
--- Logging error ---
Traceback (most recent call last):
  File "/home/ccl/Desktop/RR/FedOps2/fedopstest/app.py", line 148, in fl_client_start
    await loop.run_in_executor(None, client_start)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 627, in start_numpy_client
    start_client(
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 184, in start_client
    start_client_internal(
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 395, in start_client_internal
    message = receive()
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/grpc_client/connection.py", line 142, in receive
    proto = next(server_message_iterator)
  File "/home/ccl/.local/lib/python3.9/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
  File "/home/ccl/.local/lib/python3.9/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.9.201.228:40002: Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.9.201.228:40002: Socket closed", grpc_status:14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/ccl/Desktop/RR/FedOps2/fedopstest/app.py", line 205, in fl_client_start
    logging.info('[E][PC0002] learning', e)
Message: '[E][PC0002] learning'
Arguments: (<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.9.201.228:40002: Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.9.201.228:40002: Socket closed", grpc_status:14}"
>,)
[2025-09-30 10:51:24,478][root][INFO] - notify_fail start
[2025-09-30 10:51:24,497][root][ERROR] - trainFin
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    await response(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/responses.py", line 160, in __call__
    await self.background()
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/background.py", line 41, in __call__
    await task()
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/ccl/Desktop/RR/FedOps2/fedopstest/app.py", line 208, in fl_client_start
    raise e
  File "/home/ccl/Desktop/RR/FedOps2/fedopstest/app.py", line 148, in fl_client_start
    await loop.run_in_executor(None, client_start)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 627, in start_numpy_client
    start_client(
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 184, in start_client
    start_client_internal(
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 395, in start_client_internal
    message = receive()
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/grpc_client/connection.py", line 142, in receive
    proto = next(server_message_iterator)
  File "/home/ccl/.local/lib/python3.9/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
  File "/home/ccl/.local/lib/python3.9/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.9.201.228:40002: Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.9.201.228:40002: Socket closed", grpc_status:14}"
>
[32mINFO[0m:     127.0.0.1:44098 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:44110 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:39318 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:33154 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:33158 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:33000 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58490 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58504 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:55636 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:39142 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:39154 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:51274 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:57808 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:57812 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:37714 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:50686 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:50698 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:59504 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:49390 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:49394 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:41820 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:44240 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:44250 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:49912 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:49926 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:52234 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:59648 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:59650 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:60586 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:59012 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:59024 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:59418 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:49898 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:49908 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:50460 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:40778 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:40788 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:47308 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:43276 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:43284 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:37356 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:37382 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:37398 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:47058 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:48066 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:48070 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:46032 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:46048 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:37140 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:52412 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:52418 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:36632 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:45108 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:45114 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:47082 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:54432 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:54434 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:54698 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:56746 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:56762 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:55270 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:37504 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:37508 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[2025-09-30 10:58:21,277][root][INFO] - bulid model
[2025-09-30 10:58:21,277][root][INFO] - FL start
[2025-09-30 10:58:21,285][client_api][INFO] - FL_server_IP:port - ccl.gachon.ac.kr:40032
[32mINFO[0m:     127.0.0.1:47106 - "[1mPOST /start HTTP/1.1[0m" [32m200 OK[0m
[2025-09-30 10:58:21,287][root][INFO] - FL learning ready
[2025-09-30 10:58:21,287][root][INFO] - fl_task_id: cluster2
[2025-09-30 10:58:21,287][root][INFO] - dataset: MNIST
[2025-09-30 10:58:21,287][root][INFO] - output_size: 10
[2025-09-30 10:58:21,288][root][INFO] - validation_split: 0.2
[2025-09-30 10:58:21,288][root][INFO] - model_type: Pytorch
[2025-09-30 10:58:21,288][root][INFO] - wandb_key: 38f6cf3c2c37660d42ebfe8ab434b72d34be3b31
[2025-09-30 10:58:21,288][root][INFO] - wandb_account: rirakang@gachon.ac.kr
[34m[1mwandb[0m: [33mWARNING[0m Calling wandb.login() after wandb.init() has no effect.
[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated.
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below:
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[2025-09-30 10:58:21,294][flwr][WARNING] - DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated.
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below:
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[2025-09-30 10:58:21,295][flwr][WARNING] - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[2025-09-30 10:58:21,297][flwr][DEBUG] - Opened insecure gRPC connection (no certificates were passed)
[2025-09-30 10:58:21,338][flwr][DEBUG] - ChannelConnectivity.IDLE
[2025-09-30 10:58:21,341][flwr][DEBUG] - ChannelConnectivity.CONNECTING
[2025-09-30 10:58:21,342][flwr][DEBUG] - ChannelConnectivity.READY
[2025-09-30 11:05:32,391][flwr][DEBUG] - gRPC channel closed
--- Logging error ---
Traceback (most recent call last):
  File "/home/ccl/Desktop/RR/FedOps2/fedopstest/app.py", line 148, in fl_client_start
    await loop.run_in_executor(None, client_start)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 627, in start_numpy_client
    start_client(
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 184, in start_client
    start_client_internal(
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 395, in start_client_internal
    message = receive()
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/grpc_client/connection.py", line 142, in receive
    proto = next(server_message_iterator)
  File "/home/ccl/.local/lib/python3.9/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
  File "/home/ccl/.local/lib/python3.9/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:"Socket closed"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/ccl/Desktop/RR/FedOps2/fedopstest/app.py", line 205, in fl_client_start
    logging.info('[E][PC0002] learning', e)
Message: '[E][PC0002] learning'
Arguments: (<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:"Socket closed"}"
>,)
--- Logging error ---
Traceback (most recent call last):
  File "/home/ccl/Desktop/RR/FedOps2/fedopstest/app.py", line 148, in fl_client_start
    await loop.run_in_executor(None, client_start)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 627, in start_numpy_client
    start_client(
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 184, in start_client
    start_client_internal(
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 395, in start_client_internal
    message = receive()
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/grpc_client/connection.py", line 142, in receive
    proto = next(server_message_iterator)
  File "/home/ccl/.local/lib/python3.9/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
  File "/home/ccl/.local/lib/python3.9/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:"Socket closed"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/ccl/Desktop/RR/FedOps2/fedopstest/app.py", line 205, in fl_client_start
    logging.info('[E][PC0002] learning', e)
Message: '[E][PC0002] learning'
Arguments: (<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:"Socket closed"}"
>,)
[2025-09-30 11:05:32,397][root][INFO] - notify_fail start
[2025-09-30 11:05:32,414][root][ERROR] - trainFin
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    await response(scope, receive, send)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/responses.py", line 160, in __call__
    await self.background()
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/background.py", line 41, in __call__
    await task()
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/ccl/Desktop/RR/FedOps2/fedopstest/app.py", line 208, in fl_client_start
    raise e
  File "/home/ccl/Desktop/RR/FedOps2/fedopstest/app.py", line 148, in fl_client_start
    await loop.run_in_executor(None, client_start)
  File "/home/ccl/anaconda3/envs/rrfedops/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 627, in start_numpy_client
    start_client(
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 184, in start_client
    start_client_internal(
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/app.py", line 395, in start_client_internal
    message = receive()
  File "/home/ccl/.local/lib/python3.9/site-packages/flwr/compat/client/grpc_client/connection.py", line 142, in receive
    proto = next(server_message_iterator)
  File "/home/ccl/.local/lib/python3.9/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
  File "/home/ccl/.local/lib/python3.9/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:"Socket closed"}"
>
[32mINFO[0m:     127.0.0.1:51672 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:41536 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:52812 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:52820 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:48136 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:57382 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:57388 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:54422 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:55424 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:55440 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:53776 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:51718 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:51724 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:47782 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:55272 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:55282 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:36272 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:57138 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:57150 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:54060 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:40996 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:41004 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:44414 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:44426 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:43196 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:35376 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:35388 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:50832 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:42340 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:42356 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:46924 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:60766 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:60776 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:40816 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58254 - "[1mGET /online HTTP/1.1[0m" [32m200 OK[0m
[2025-09-30 11:09:25,061][root][INFO] - bulid model
[2025-09-30 11:09:25,062][root][INFO] - FL start
[2025-09-30 11:09:25,071][client_api][INFO] - FL_server_IP:port - ccl.gachon.ac.kr:40032
[32mINFO[0m:     127.0.0.1:58266 - "[1mPOST /start HTTP/1.1[0m" [32m200 OK[0m
[2025-09-30 11:09:25,073][root][INFO] - FL learning ready
[2025-09-30 11:09:25,073][root][INFO] - fl_task_id: cluster2
[2025-09-30 11:09:25,073][root][INFO] - dataset: MNIST
[2025-09-30 11:09:25,074][root][INFO] - output_size: 10
[2025-09-30 11:09:25,074][root][INFO] - validation_split: 0.2
[2025-09-30 11:09:25,074][root][INFO] - model_type: Pytorch
[2025-09-30 11:09:25,074][root][INFO] - wandb_key: 38f6cf3c2c37660d42ebfe8ab434b72d34be3b31
[2025-09-30 11:09:25,074][root][INFO] - wandb_account: rirakang@gachon.ac.kr
[34m[1mwandb[0m: [33mWARNING[0m Calling wandb.login() after wandb.init() has no effect.
[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated.
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below:
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[2025-09-30 11:09:25,081][flwr][WARNING] - DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated.
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below:
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[2025-09-30 11:09:25,082][flwr][WARNING] - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[2025-09-30 11:09:25,084][flwr][DEBUG] - Opened insecure gRPC connection (no certificates were passed)
[2025-09-30 11:09:25,115][flwr][DEBUG] - ChannelConnectivity.IDLE
[2025-09-30 11:09:25,116][flwr][DEBUG] - ChannelConnectivity.CONNECTING
[2025-09-30 11:09:25,120][flwr][DEBUG] - ChannelConnectivity.READY
[92mINFO [0m:
[2025-09-30 11:14:44,680][flwr][INFO] -
[92mINFO [0m:      Received: train message 58e5c588-09fe-45a5-9afa-0665f0aaa48a
[2025-09-30 11:14:44,681][flwr][INFO] - Received: train message 58e5c588-09fe-45a5-9afa-0665f0aaa48a
[2025-09-30 11:14:44,703][client_api][INFO] - [cluster-upsert] success (task_id=cluster2, mac=43:56:51:a9:43:53, cluster_id=0)
Starting evalutation...
Testing: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1467/1467 [00:02<00:00, 551.74batch/s]
Starting evalutation...
Testing: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 54.41batch/s]
[2025-09-30 11:15:09,608][client_fl][INFO] - train_performance - {"fl_task_id": "cluster2", "client_mac": "43:56:51:a9:43:53", "client_name": "ccl-x-server", "round": 1, "gl_model_v": 1, "train_loss": 0.12560305100689173, "train_accuracy": 0.9665104388581167, "train_f1_score": 0.9651983847896332, "val_loss": 0.13010902200704036, "val_accuracy": 0.9631776338220253, "val_f1_score": 0.9624638188991682, "train_time": 24.90222144126892, "wandb_name": "ccl-x-server-v0(2025-09-30 10:47:19.402020)", "cluster_id": 0}
[92mINFO [0m:      Sent reply
[2025-09-30 11:15:09,669][flwr][INFO] - Sent reply
[92mINFO [0m:
[2025-09-30 11:15:15,278][flwr][INFO] -
[92mINFO [0m:      Received: evaluate message 8cc7f658-0b74-484d-8299-3d01881b4060
[2025-09-30 11:15:15,279][flwr][INFO] - Received: evaluate message 8cc7f658-0b74-484d-8299-3d01881b4060
Starting evalutation...
Testing: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 79/79 [00:01<00:00, 55.34batch/s]
[2025-09-30 11:15:16,734][client_fl][INFO] - test - {"fl_task_id": "cluster2", "client_mac": "43:56:51:a9:43:53", "client_name": "ccl-x-server", "round": 1, "test_loss": 5.114441630206531, "test_accuracy": 0.4847, "gl_model_v": 1, "wandb_name": "ccl-x-server-v0(2025-09-30 10:47:19.402020)"}
[92mINFO [0m:      Sent reply
[2025-09-30 11:15:16,748][flwr][INFO] - Sent reply
[92mINFO [0m:
[2025-09-30 11:15:17,842][flwr][INFO] -
[92mINFO [0m:      Received: train message 71e0d550-a59c-41ca-a642-8d21452f1c8e
[2025-09-30 11:15:17,843][flwr][INFO] - Received: train message 71e0d550-a59c-41ca-a642-8d21452f1c8e
[2025-09-30 11:15:17,863][client_api][INFO] - [cluster-upsert] success (task_id=cluster2, mac=43:56:51:a9:43:53, cluster_id=0)
Starting evalutation...
Testing: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1467/1467 [00:02<00:00, 566.75batch/s]
Starting evalutation...
Testing: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 56.54batch/s]
[2025-09-30 11:15:34,027][client_fl][INFO] - train_performance - {"fl_task_id": "cluster2", "client_mac": "43:56:51:a9:43:53", "client_name": "ccl-x-server", "round": 2, "gl_model_v": 1, "train_loss": 0.08062034313206388, "train_accuracy": 0.9769066893907116, "train_f1_score": 0.9755965410856835, "val_loss": 0.08961956818466602, "val_accuracy": 0.9727241732015002, "val_f1_score": 0.9720375487433826, "train_time": 16.160831689834595, "wandb_name": "ccl-x-server-v0(2025-09-30 10:47:19.402020)", "cluster_id": 0}
[92mINFO [0m:      Sent reply
[2025-09-30 11:15:34,065][flwr][INFO] - Sent reply
[92mINFO [0m:
[2025-09-30 11:15:39,722][flwr][INFO] -
[92mINFO [0m:      Received: evaluate message 276cb2c5-8968-41bd-a903-2f2b97661e25
[2025-09-30 11:15:39,723][flwr][INFO] - Received: evaluate message 276cb2c5-8968-41bd-a903-2f2b97661e25
Starting evalutation...
Testing: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 79/79 [00:01<00:00, 55.12batch/s]
[2025-09-30 11:15:41,185][client_fl][INFO] - test - {"fl_task_id": "cluster2", "client_mac": "43:56:51:a9:43:53", "client_name": "ccl-x-server", "round": 2, "test_loss": 6.924108583715897, "test_accuracy": 0.4959, "gl_model_v": 1, "wandb_name": "ccl-x-server-v0(2025-09-30 10:47:19.402020)"}
[92mINFO [0m:      Sent reply
[2025-09-30 11:15:41,196][flwr][INFO] - Sent reply
[92mINFO [0m:
[2025-09-30 11:15:41,614][flwr][INFO] -
[92mINFO [0m:      Received: reconnect message f9f689a6-a570-4aed-9b53-b54d7866ba36
[2025-09-30 11:15:41,614][flwr][INFO] - Received: reconnect message f9f689a6-a570-4aed-9b53-b54d7866ba36
[2025-09-30 11:15:41,629][flwr][DEBUG] - gRPC channel closed
[92mINFO [0m:      Disconnect and shut down
[2025-09-30 11:15:41,630][flwr][INFO] - Disconnect and shut down
[2025-09-30 11:15:41,630][root][INFO] - fl learning finished
